// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using MyInstaPrepWebApp.Models;
using Newtonsoft.Json.Linq;

namespace MyInstaPrepWebApp.Models
{
    public static partial class UserCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<User> DeserializeJson(JToken inputObject)
        {
            IList<User> deserializedObject = new List<User>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                User user = new User();
                user.DeserializeJson(iListValue);
                deserializedObject.Add(user);
            }
            return deserializedObject;
        }
    }
}
