// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using MyInstaPrepWebApp;
using MyInstaPrepWebApp.Models;

namespace MyInstaPrepWebApp
{
    public static partial class DefaultExtensions
    {
        /// <param name='operations'>
        /// Reference to the MyInstaPrepWebApp.IDefault.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static User GetUser(this IDefault operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDefault)s).GetUserAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyInstaPrepWebApp.IDefault.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<User> GetUserAsync(this IDefault operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<MyInstaPrepWebApp.Models.User> result = await operations.GetUserWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the MyInstaPrepWebApp.IDefault.
        /// </param>
        public static IList<User> GetUsers(this IDefault operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDefault)s).GetUsersAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the MyInstaPrepWebApp.IDefault.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<User>> GetUsersAsync(this IDefault operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<MyInstaPrepWebApp.Models.User>> result = await operations.GetUsersWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
