// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using MyInstaPrepWebApp;

namespace MyInstaPrepWebApp
{
    public partial class MyInstaPrepAPI : ServiceClient<MyInstaPrepAPI>, IMyInstaPrepAPI
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IDefault _defaultVariable;
        
        public virtual IDefault Default
        {
            get { return this._defaultVariable; }
        }
        
        private IUsers _users;
        
        public virtual IUsers Users
        {
            get { return this._users; }
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        public MyInstaPrepAPI()
            : base()
        {
            this._defaultVariable = new Default(this);
            this._users = new Users(this);
            this._baseUri = new Uri("https://microsoft-apiapp613d756d6fa04ea0b13863e95e4fd34f.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public MyInstaPrepAPI(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._defaultVariable = new Default(this);
            this._users = new Users(this);
            this._baseUri = new Uri("https://microsoft-apiapp613d756d6fa04ea0b13863e95e4fd34f.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public MyInstaPrepAPI(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._defaultVariable = new Default(this);
            this._users = new Users(this);
            this._baseUri = new Uri("https://microsoft-apiapp613d756d6fa04ea0b13863e95e4fd34f.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public MyInstaPrepAPI(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public MyInstaPrepAPI(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the MyInstaPrepAPI class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public MyInstaPrepAPI(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
